plugins {
    id("awesome.androidapp.plugin")
}

dependencies {
    implementation(project(":ui:group-identity"))
    implementation(project(":ui:message-identity"))
    implementation(project(":ui:notification-identity"))
    implementation(project(":ui:setting-identity"))
    implementation(project(":ui:account-identity"))
    implementation(project(":ui:session-identity"))
    implementation(project(":ui:analytics-identity"))
    implementation(project(":ui:report-identity"))
    implementation(project(":ui:log-identity"))
    implementation(project(":ui:status-identity"))
    implementation(project(":ui:metric-identity"))
    implementation(project(":ui:task-identity"))
    implementation(project(":ui:calendar-identity"))
    implementation(project(":ui:event-identity"))
    implementation(project(":ui:alarm-identity"))
    implementation(project(":ui:timer-identity"))
    implementation(project(":ui:file-identity"))
    implementation(project(":ui:document-identity"))
    implementation(project(":ui:note-identity"))
    implementation(project(":ui:todo-identity"))
    implementation(project(":ui:list-identity"))
    implementation(project(":ui:map-identity"))
    implementation(project(":ui:weather-identity"))
    implementation(project(":ui:forecast-identity"))
    implementation(project(":ui:news-identity"))
    implementation(project(":ui:article-identity"))
    implementation(project(":ui:podcast-identity"))
    implementation(project(":ui:video-identity"))
    implementation(project(":ui:photo-identity"))
    implementation(project(":ui:gallery-identity"))
    implementation(project(":ui:media-identity"))
    implementation(project(":ui:audio-identity"))
    implementation(project(":ui:playlist-identity"))
    implementation(project(":ui:push-checkout"))
    implementation(project(":ui:contact-checkout"))
    implementation(project(":ui:login-checkout"))
    implementation(project(":ui:identity-checkout"))
    implementation(project(":ui:checkout-checkout"))
    implementation(project(":ui:cart-checkout"))
    implementation(project(":ui:user-checkout"))
    implementation(project(":ui:profile-checkout"))
    implementation(project(":ui:feed-checkout"))
    implementation(project(":ui:comment-checkout"))
    implementation(project(":ui:post-checkout"))
    implementation(project(":ui:search-checkout"))
    implementation(project(":ui:location-checkout"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(project.dependencies.platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}