pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("com.fueledbycaffeine.spotlight") version "1.4.1"
}
rootProject.name = "flat-130-gradle_9_2_1-shape-test-project"

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
} 
include (":core:push")
include (":core:contact")
include (":core:login")
include (":core:identity")
include (":core:checkout")
include (":core:cart")
include (":core:user")
include (":core:profile")
include (":core:feed")
include (":core:comment")
include (":core:post")
include (":core:search")
include (":core:location")
include (":core:network")
include (":core:sync")
include (":core:share")
include (":core:group")
include (":core:message")
include (":core:notification")
include (":core:setting")
include (":core:account")
include (":core:session")
include (":core:analytics")
include (":core:report")
include (":core:log")
include (":core:status")
include (":core:metric")
include (":core:task")
include (":core:calendar")
include (":core:event")
include (":core:alarm")
include (":core:timer")
include (":core:file")
include (":core:document")
include (":core:note")
include (":core:todo")
include (":core:list")
include (":core:map")
include (":core:weather")
include (":core:forecast")
include (":core:news")
include (":core:article")
include (":core:podcast")
include (":core:video")
include (":core:photo")
include (":core:gallery")
include (":core:media")
include (":core:audio")
include (":core:playlist")
include (":core:push-contact")
include (":core:contact-contact")
include (":core:login-contact")
include (":core:identity-contact")
include (":core:checkout-contact")
include (":core:cart-contact")
include (":core:user-contact")
include (":core:profile-contact")
include (":core:feed-contact")
include (":core:comment-contact")
include (":core:post-contact")
include (":core:search-contact")
include (":core:location-contact")
include (":core:network-contact")
include (":core:sync-contact")
include (":core:share-contact")
include (":core:group-contact")
include (":core:message-contact")
include (":core:notification-contact")
include (":core:setting-contact")
include (":core:account-contact")
include (":core:session-contact")
include (":core:analytics-contact")
include (":core:report-contact")
include (":core:log-contact")
include (":core:status-contact")
include (":core:metric-contact")
include (":core:task-contact")
include (":core:calendar-contact")
include (":core:event-contact")
include (":core:alarm-contact")
include (":core:timer-contact")
include (":core:file-contact")
include (":core:document-contact")
include (":core:note-contact")
include (":core:todo-contact")
include (":core:list-contact")
include (":core:map-contact")
include (":core:weather-contact")
include (":core:forecast-contact")
include (":core:news-contact")
include (":core:article-contact")
include (":core:podcast-contact")
include (":core:video-contact")
include (":core:photo-contact")
include (":core:gallery-contact")
include (":core:media-contact")
include (":core:audio-contact")
include (":core:playlist-contact")
include (":core:push-login")
include (":core:contact-login")
include (":core:login-login")
include (":core:identity-login")
include (":core:checkout-login")
include (":core:cart-login")
include (":core:user-login")
include (":core:profile-login")
include (":core:feed-login")
include (":core:comment-login")
include (":core:post-login")
include (":core:search-login")
include (":core:location-login")
include (":core:network-login")
include (":core:sync-login")
include (":core:share-login")
include (":core:group-login")
include (":core:message-login")
include (":core:notification-login")
include (":core:setting-login")
include (":core:account-login")
include (":core:session-login")
include (":core:analytics-login")
include (":core:report-login")
include (":core:log-login")
include (":core:status-login")
include (":core:metric-login")
include (":core:task-login")
include (":core:calendar-login")
include (":core:event-login")
include (":core:alarm-login")
include (":core:timer-login")
include (":feature:file-login")