initscript {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath "io.github.milkyway.gradle:gradle-plugin:@GRADLE_PLUGIN_VERSION@"
    }
}

gradle.beforeProject { project ->
    if (project == project.rootProject) {
        project.pluginManager.apply(io.github.milkyway.gradle.MilkyWayPlugin)
    }
}