plugins {
    id("awesome.androidapp.plugin")
}

dependencies {
    implementation(project(":ui:report-contact"))
    implementation(project(":ui:log-contact"))
    implementation(project(":ui:status-contact"))
    implementation(project(":ui:metric-contact"))
    implementation(project(":ui:task-contact"))
    implementation(project(":ui:calendar-contact"))
    implementation(project(":ui:event-contact"))
    implementation(project(":ui:alarm-contact"))
    implementation(project(":ui:timer-contact"))
    implementation(project(":ui:file-contact"))
    implementation(project(":ui:document-contact"))
    implementation(project(":ui:note-contact"))
    implementation(project(":ui:todo-contact"))
    implementation(project(":ui:list-contact"))
    implementation(project(":ui:map-contact"))
    implementation(project(":ui:weather-contact"))
    implementation(project(":ui:forecast-contact"))
    implementation(project(":ui:news-contact"))
    implementation(project(":ui:article-contact"))
    implementation(project(":ui:podcast-contact"))
    implementation(project(":ui:video-contact"))
    implementation(project(":ui:photo-contact"))
    implementation(project(":ui:gallery-contact"))
    implementation(project(":ui:media-contact"))
    implementation(project(":ui:audio-contact"))
    implementation(project(":ui:playlist-contact"))
    implementation(project(":ui:push-login"))
    implementation(project(":ui:contact-login"))
    implementation(project(":ui:login-login"))
    implementation(project(":ui:identity-login"))
    implementation(project(":ui:checkout-login"))
    implementation(project(":ui:cart-login"))
    implementation(project(":ui:user-login"))
    implementation(project(":ui:profile-login"))
    implementation(project(":ui:feed-login"))
    implementation(project(":ui:comment-login"))
    implementation(project(":ui:post-login"))
    implementation(project(":ui:search-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(project.dependencies.platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    

}