pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id("com.fueledbycaffeine.spotlight") version "1.4.1"
}
rootProject.name = "inverse_triangle-110-gradle_8_12_1-shape-test-project"

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
} 
include (":core:push")
include (":core:contact")
include (":core:login")
include (":feature:identity")
include (":feature:checkout")
include (":feature:cart")
include (":feature:user")
include (":domain:profile")
include (":domain:feed")
include (":domain:comment")
include (":domain:post")
include (":repository:search")
include (":repository:location")
include (":repository:network")
include (":repository:sync")
include (":repository:share")
include (":model:group")
include (":model:message")
include (":model:notification")
include (":model:setting")
include (":model:account")
include (":model:session")
include (":entity:analytics")
include (":entity:report")
include (":entity:log")
include (":entity:status")
include (":entity:metric")
include (":entity:task")
include (":entity:calendar")
include (":entity:event")
include (":data:alarm")
include (":data:timer")
include (":data:file")
include (":data:document")
include (":data:note")
include (":data:todo")
include (":data:list")
include (":data:map")
include (":data:weather")
include (":data:forecast")
include (":api:news")
include (":api:article")
include (":api:podcast")
include (":api:video")
include (":api:photo")
include (":api:gallery")
include (":api:media")
include (":api:audio")
include (":api:playlist")
include (":api:push-contact")
include (":api:contact-contact")
include (":api:login-contact")
include (":api:identity-contact")
include (":presentation:checkout-contact")
include (":presentation:cart-contact")
include (":presentation:user-contact")
include (":presentation:profile-contact")
include (":presentation:feed-contact")
include (":presentation:comment-contact")
include (":presentation:post-contact")
include (":presentation:search-contact")
include (":presentation:location-contact")
include (":presentation:network-contact")
include (":presentation:sync-contact")
include (":presentation:share-contact")
include (":presentation:group-contact")
include (":presentation:message-contact")
include (":presentation:notification-contact")
include (":presentation:setting-contact")
include (":presentation:account-contact")
include (":presentation:session-contact")
include (":presentation:analytics-contact")
include (":ui:report-contact")
include (":ui:log-contact")
include (":ui:status-contact")
include (":ui:metric-contact")
include (":ui:task-contact")
include (":ui:calendar-contact")
include (":ui:event-contact")
include (":ui:alarm-contact")
include (":ui:timer-contact")
include (":ui:file-contact")
include (":ui:document-contact")
include (":ui:note-contact")
include (":ui:todo-contact")
include (":ui:list-contact")
include (":ui:map-contact")
include (":ui:weather-contact")
include (":ui:forecast-contact")
include (":ui:news-contact")
include (":ui:article-contact")
include (":ui:podcast-contact")
include (":ui:video-contact")
include (":ui:photo-contact")
include (":ui:gallery-contact")
include (":ui:media-contact")
include (":ui:audio-contact")
include (":ui:playlist-contact")
include (":ui:push-login")
include (":ui:contact-login")
include (":ui:login-login")
include (":ui:identity-login")
include (":ui:checkout-login")
include (":ui:cart-login")
include (":ui:user-login")
include (":ui:profile-login")
include (":ui:feed-login")
include (":ui:comment-login")
include (":ui:post-login")
include (":ui:search-login")
include (":app:app")