name: Build & Publish Milkyway Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
      - name: Build IDEA plugin
        id: artifact
        run: |
          cd milkyway-plugin
          chmod +x gradlew
          ./gradlew :idea-plugin:buildPlugin --no-configuration-cache
          ABS_FILE_PATH=$(find ./idea-plugin/build/distributions -name "*.zip" | head -n 1 | xargs realpath)
          FILE_NAME=$(basename "$ABS_FILE_PATH")
          FILE_NAME=${FILE_NAME:0:-4}
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "file_abs_path=$ABS_FILE_PATH" >> $GITHUB_OUTPUT
      - name: Check if artifact exist
        run: ls ./milkyway-plugin/idea-plugin/build/distributions
      - name: Check output
        run: |
          echo "${{ steps.artifact.outputs.file_name }}"
          echo "${{ steps.artifact.outputs.file_abs_path }}"
      # Store an already-built plugin as an artifact for downloading
      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact.outputs.file_name }}
          path: ${{ steps.artifact.outputs.file_abs_path }}
          archive: false
          if-no-files-found: error
          overwrite: true
          retention-days: 7
      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
      - name: Output artifact URL
        run: echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
